-- NO_IMPORTS

FREE_GUN_TO_DISTRIBUTE = "remington"
FREE_CAR_TO_DISTRIBUTE = "countach"
FREE_MONEY_TO_DISTRIBUTE = 10000

MAX_MONEY = 9999999
MAX_KARMA = 2.0
MAX_AMMO_PRICE = 750
LOADOUT_CHANGE_PRICE = 500